### ISSUE TITLE
Selected text in the editor can be used as default value for new entry 

### ISSUE THREAD

**Issue by pavelsuk** [natterstefan/vscode-toggl-extension#14]
# Feature Request

When working with project, user should be able to pre-select the text for new entry. Ideally - based on something that's part of the project and is open in the editor.  

## Basic example

I will submit pull request for it. 

## Motivation

Can be used for tracking the work on specific tasks (from TODO+ extension).

**Comment by natterstefan** [comment]
Hi @pavelsuk, sounds very interesting. I'll check out the PR.

**Comment by natterstefan** [comment]
Hey @pavelsuk, FYI - your changes from https://github.com/natterstefan/vscode-toggl-extension/pull/15 were released as [v0.4.0](https://github.com/natterstefan/vscode-toggl-extension/blob/master/CHANGELOG.md#20191229-040).
